AY2122S1-CS2103T-F11-2/tp

docs/UserGuide.md
=> Update Quick Start and Viewing Help section in the User Guide for v1.1

docs/UserGuide.md
=> Update Saving and Loading Data section in the User Guide for v1.1

docs/UserGuide.md
Delete command in User Guide updated for RecruitIn purposes.
=> Update delete command in User Guide

docs/UserGuide.md
=> Delete delete command for employers in User Guide #33

docs/UserGuide.md
=> Delete employer part in UG for add command

docs/DeveloperGuide.md
=> Update user stories and use cases for delete functionality in Developer Guide

src/main/java/seedu/address/logic/parser/FindCommandParser.java, src/main/java/seedu/address/ui/PersonCard.java
Add PREFIX_EXPERIENCE argument to argMultiMap in FindCommandParser, Delete dollar sign for experience in PersonCard
=> Add missing parts in the previous commit

src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java, src/test/java/seedu/address/logic/commands/FindCommandTest.java, src/test/java/seedu/address/logic/parser/ArgumentTokenizerTest.java, src/test/java/seedu/address/model/person/RoleContainsKeywordsPredicateTest.java, src/test/java/seedu/address/model/person/RoleTest.java
=> Add unit tests for RoleContainsKeywordPredicate and ArgumentTokenizer classes

src/test/java/seedu/address/model/person/EmailContainsKeywordsPredicateTest.java
=> Update EmailContainsKeywordsPredicate test cases

src/test/java/seedu/address/model/person/ExperienceContainsKeywordsPredicateTest.java, src/test/java/seedu/address/model/person/ExperienceTest.java
=> Branch experience test cases

docs/UserGuide.md
=> Add EmploymentType section for Find command in UserGuide

docs/UserGuide.md
=> Update Level of Education section for Find command in User Guide

src/main/java/seedu/address/model/person/ExpectedSalary.java, src/test/java/seedu/address/model/person/ExpectedSalaryTest.java
=> Invalidate long values for `ExpectedSalary`

docs/UserGuide.md
=> Add experience in find command section of the UG  

src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
=> Add valid test case in FindCommandParserTest

src/main/java/seedu/address/model/person/EmploymentType.java
=> Modify Add and Edit command to be case insensitive for Employment Type category

src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/commands/ShowCommand.java, src/main/java/seedu/address/logic/parser/AddCommandParser.java, src/main/java/seedu/address/logic/parser/CliSyntax.java, src/main/java/seedu/address/logic/parser/EditCommandParser.java, src/main/java/seedu/address/logic/parser/FindCommandParser.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/logic/parser/PrefixSyntax.java, src/main/java/seedu/address/logic/parser/ShowCommandParser.java, src/main/java/seedu/address/model/interview/Interview.java, src/main/java/seedu/address/model/interview/InterviewContainsKeywordsPredicate.java, src/main/java/seedu/address/model/person/Person.java, src/main/java/seedu/address/model/util/SampleDataUtil.java, src/main/java/seedu/address/storage/JsonAdaptedPerson.java, src/main/java/seedu/address/ui/PersonCard.java, src/main/resources/view/PersonListCard.fxml, src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json, src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json, src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java, src/test/java/seedu/address/logic/parser/EditCommandParserTest.java, src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java, src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java, src/test/java/seedu/address/testutil/PersonBuilder.java, src/test/java/seedu/address/testutil/PersonUtil.java, src/test/java/seedu/address/testutil/TypicalPersons.java
#157 
- Add Interview package under model
- Add Optional<Interview> as a field to Person 
- Modify Add/Edit/Show/Find command and UI to make new feature functional 
- Add empty or non-empty interview to existing person models 
- Modify test cases to accomodate optional interview 
- Update User Guide/ Developer Guide for interview feature and related commands 
- Add more test cases for new methods added 
- Use assertions
=> Add Interview

docs/DeveloperGuide.md, docs/UserGuide.md, src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java, src/main/java/seedu/address/logic/parser/ShowCommandParser.java, src/test/java/seedu/address/logic/commands/ShowCommandTest.java, src/test/java/seedu/address/logic/parser/ArgumentTokenizerTest.java, src/test/java/seedu/address/logic/parser/ShowCommandParserTest.java
=> Modify `ShowCommandParser` to take only first `Prefix`

src/main/resources/view/DarkTheme.css
=> Change to blue theme for UI

docs/UserGuide.md
=> Add prefix input specification for Experience and Interview in UG

docs/UserGuide.md, src/main/java/seedu/address/model/interview/Interview.java
fixes #268 
fixes #256 
fixes #262
=> Fix interview invalid date bug, update interview and experience in UG

src/main/java/seedu/address/commons/util/StringUtil.java, src/main/java/seedu/address/model/person/Experience.java, src/main/java/seedu/address/model/person/ExperienceContainsKeywordsPredicate.java, src/test/java/seedu/address/commons/util/StringUtilTest.java, src/test/java/seedu/address/model/person/ExperienceTest.java
=> Change year of experience to double, with restriction of 1 d.p.

src/main/java/seedu/address/logic/commands/EditCommand.java
=> Fix Done status changes after editing bug

docs/UserGuide.md, src/main/java/seedu/address/logic/parser/PrefixSyntax.java
Fixes #254 
Fixes #261 
Updating the Quick Start section of UG
Fixes #255 
Adding clear command to command summary
Fixes #259 
Fixes #283 
Clarify the level of education and done section under Find command
=> Fix PED UG Issues

src/main/java/seedu/address/model/interview/Interview.java
Fixes #284 
* Updated interview message constraint to be same as UG
=> Update interview message constraints

docs/UserGuide.md
Fixes #251 
Fixes #257 
* Updated spelling to be standardise British spelling 
* Updated delete command description in Quick Start, as tester understood the old description to mean only Mary is left in the list. It now specifically mentions that Mary is deleted, and only John remains.
=> Update UG based on PE bugs

docs/DeveloperGuide.md
Fixes #312 
* Add alternative options for filter interview implementation
* Add justification for current choice of option for filter interview implementation
=> Add design consideration for Filter Interview command

docs/DeveloperGuide.md, docs/diagrams/FindCommandActivityDiagram.puml
fixes #345
- Modify find command activity diagram
- Add design consideration
- Changed order to be consistent with UG
=> Branch dg modification

docs/DeveloperGuide.md, docs/UserGuide.md
=> Add intro to DG and change links and wording in UG

docs/DeveloperGuide.md
Fixes #363 
1) Add manual testing for mark command
2) Add manual testing for unmark command
3) Add manual testing for delete_marked command
=> Add manual testing for mark, unmark and delete marked in DG

docs/DeveloperGuide.md, docs/SettingUp.md, docs/UserGuide.md
=> Add acknowledgements and update code links in DG

docs/UserGuide.md
=> Add warning against editing preferences.json

docs/team/tohweijie01.md
=> Update PPP - Wei Jie

docs/team/twothicc.md
=> Update PPP - Chen En

src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/commands/FindCommand.java, src/main/java/seedu/address/logic/commands/ShowCommand.java, src/main/java/seedu/address/logic/parser/AddCommandParser.java, src/main/java/seedu/address/logic/parser/EditCommandParser.java, src/main/java/seedu/address/logic/parser/FindCommandParser.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/person/RoleContainsKeywordsPredicate.java
=> Add javadocs and change usage message for show command

src/main/java/seedu/address/model/interview/Interview.java
=> Refine javadoc and add one assertion in `Interview`

src/main/java/seedu/address/model/util/SampleDataUtil.java
Fixes #422 
* Added 20th applicant
=> Add 20th sample data

docs/DeveloperGuide.md, docs/SettingUp.md, docs/UserGuide.md
=> Update link to app in UG and add about section to DG

docs/index.md
Fixes #429 
* Updated index.md acknowledgements to be same as DG
=> Update index.md acknowledgements to match DG acknowledgements

docs/DeveloperGuide.md, docs/UserGuide.md
=> Spelling issues in UG and DG 

src/main/java/seedu/address/model/person/EmploymentType.java, src/main/java/seedu/address/model/person/EmploymentTypeContainsKeywordsPredicate.java
Fixes #431 
* Added javadocs for EmploymentType
* Added javadocs for EmploymentTypeContainsKeywords Predicate
=> Add javadocs for EmploymentType
